### ISSUE TITLE
XMLStreamException: Stream encoding error

### ISSUE THREAD

**Issue by BrandonFanti** [davidpelfree/sjxlsx#13]
I have the issue when calling workbook.commit() when trying to save the file. It says there is an encoding error, but only after writing individual characters to the second sheet of the workbook. 

You can find the source on our github below, line 40 can be commented out and it runs fine.

https://github.com/nth-solutions/JavaDashboardMaster/blob/development/src/dataorganizer/SpreadSheetController.java

Heres the stack trace too:

Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: javax.xml.stream.XMLStreamException: Underlying stream encoding 'Cp1252' and input paramter for writeStartDocument() method 'UTF-8' do not match.
	at com.incesoft.tools.excel.xlsx.SimpleXLSXWorkbook$Commiter.endCommit(SimpleXLSXWorkbook.java:947)
	at com.incesoft.tools.excel.xlsx.SimpleXLSXWorkbook.commit(SimpleXLSXWorkbook.java:1089)
	at dataorganizer.SpreadSheetController.save(SpreadSheetController.java:71)
	at dataorganizer.SpreadSheetController.main(SpreadSheetController.java:41)
Caused by: java.lang.RuntimeException: javax.xml.stream.XMLStreamException: Underlying stream encoding 'Cp1252' and input paramter for writeStartDocument() method 'UTF-8' do not match.
	at com.incesoft.tools.excel.xlsx.SimpleXLSXWorkbook$Commiter.mergeSheets(SimpleXLSXWorkbook.java:980)
	at com.incesoft.tools.excel.xlsx.SimpleXLSXWorkbook$Commiter.endCommit(SimpleXLSXWorkbook.java:939)
	... 3 more
Caused by: javax.xml.stream.XMLStreamException: Underlying stream encoding 'Cp1252' and input paramter for writeStartDocument() method 'UTF-8' do not match.
	at com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeStartDocument(Unknown Source)
	at com.incesoft.tools.excel.xlsx.SheetCommentWriter.writeStart(SheetCommentWriter.java:49)
	at com.incesoft.tools.excel.xlsx.SheetCommentWriter.writeComment(SheetCommentWriter.java:128)
	at com.incesoft.tools.excel.xlsx.Sheet$SheetWriter.writeCell(Sheet.java:604)
	at com.incesoft.tools.excel.xlsx.Sheet$SheetWriter.writeRow(Sheet.java:581)
	at com.incesoft.tools.excel.xlsx.Sheet.mergeSheet(Sheet.java:665)
	at com.incesoft.tools.excel.xlsx.SimpleXLSXWorkbook$Commiter.mergeSheets(SimpleXLSXWorkbook.java:975)
	... 4 more

**Comment by BrandonFanti** [comment]
Never mind. I forgot to add a style in the sheet.modify() call. Added a null parameter and it was fixed..
